name: DEPLOY TO QA

on:
  push:
    branches:
      - dev-test-action
      - develop

jobs:
  build-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: yarn install

      - name: Code linting
        run: yarn lint

      - name: Building the project
        env:
          VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: yarn build
      
      - uses: actions/upload-artifact@v3
        if: github.ref == 'refs/heads/dev-test-action'
        with:
          path: dist
