name: DEPLOY TO QA

on:
  push:
    branches:
      - dev-test-action
  pull_request:
    branches:
      - dev-test-action
    types:
      - opened
      - ready_for_review
      - review_requested

jobs:
  build-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      
      - name: Code linting
        run: yarn lint

      - name: Installing project dependencies
        run: yarn install

      - name: Building the project
        env:
          VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: yarn build
      
      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          path: dist
