name: PRODUCTION ACTION

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - review_requested

jobs:
  build-qa:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Installing project dependencies
        run: yarn install

      - name: Code linting
        run: yarn lint

      - name: Building the project
        if: github.event_name == 'push'
        env:
          VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: yarn build
      
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          path: dist
