name: STAGING ACTION

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - opened
      - ready_for_review
      - review_requested

jobs:
  staging_deploy:
    if: github.event_name == 'push' # merged
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Installing project dependencies
        run: yarn install

      - name: Code linting
        run: yarn lint

      # - name: Code testing
      #   run: <test-command>

      - name: Building the project
        env:
          VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: yarn build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist

      # - name: Deployment
      #   run: <run-deployment-logic>
  
  staging_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Installing project dependencies
        run: yarn install

      - name: Code linting
        run: yarn lint
